package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * AccessItems generated by hbm2java
 */
public class AccessItems implements java.io.Serializable {

	private Integer id;
	private Integer controllerId;
	private Integer parentId;
	private String alias;
	private String displayName;
	private String subFunction;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public AccessItems() {
	}

	public AccessItems(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public AccessItems(Integer controllerId, Integer parentId, String alias, String displayName, String subFunction,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.controllerId = controllerId;
		this.parentId = parentId;
		this.alias = alias;
		this.displayName = displayName;
		this.subFunction = subFunction;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(Integer controllerId) {
		this.controllerId = controllerId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getSubFunction() {
		return this.subFunction;
	}

	public void setSubFunction(String subFunction) {
		this.subFunction = subFunction;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
