package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EmployeeBank generated by hbm2java
 */
public class EmployeeBank implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private String bankName;
	private Integer bankBranchNo;
	private String bankBranchName;
	private Boolean accountType;
	private String bankAccountNo;
	private Integer lastModifier;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeBank() {
	}

	public EmployeeBank(int employeeId, Date insertDatetime) {
		this.employeeId = employeeId;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeBank(int employeeId, String bankName, Integer bankBranchNo, String bankBranchName,
			Boolean accountType, String bankAccountNo, Integer lastModifier, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.employeeId = employeeId;
		this.bankName = bankName;
		this.bankBranchNo = bankBranchNo;
		this.bankBranchName = bankBranchName;
		this.accountType = accountType;
		this.bankAccountNo = bankAccountNo;
		this.lastModifier = lastModifier;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Integer getBankBranchNo() {
		return this.bankBranchNo;
	}

	public void setBankBranchNo(Integer bankBranchNo) {
		this.bankBranchNo = bankBranchNo;
	}

	public String getBankBranchName() {
		return this.bankBranchName;
	}

	public void setBankBranchName(String bankBranchName) {
		this.bankBranchName = bankBranchName;
	}

	public Boolean getAccountType() {
		return this.accountType;
	}

	public void setAccountType(Boolean accountType) {
		this.accountType = accountType;
	}

	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	public Integer getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(Integer lastModifier) {
		this.lastModifier = lastModifier;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
