package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EmployeeExperienceDetail generated by hbm2java
 */
public class EmployeeExperienceDetail implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private int experienceDetailId;
	private Integer projectId;
	private Boolean status;
	private Boolean type;
	private String description;
	private String unit;
	private Integer lastModifier;
	private Date lastModifiedTime;
	private Date lastAcceptedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeExperienceDetail() {
	}

	public EmployeeExperienceDetail(int employeeId, int experienceDetailId, Date insertDatetime) {
		this.employeeId = employeeId;
		this.experienceDetailId = experienceDetailId;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeExperienceDetail(int employeeId, int experienceDetailId, Integer projectId, Boolean status,
			Boolean type, String description, String unit, Integer lastModifier, Date lastModifiedTime,
			Date lastAcceptedTime, Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.employeeId = employeeId;
		this.experienceDetailId = experienceDetailId;
		this.projectId = projectId;
		this.status = status;
		this.type = type;
		this.description = description;
		this.unit = unit;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.lastAcceptedTime = lastAcceptedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public int getExperienceDetailId() {
		return this.experienceDetailId;
	}

	public void setExperienceDetailId(int experienceDetailId) {
		this.experienceDetailId = experienceDetailId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Integer getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(Integer lastModifier) {
		this.lastModifier = lastModifier;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Date getLastAcceptedTime() {
		return this.lastAcceptedTime;
	}

	public void setLastAcceptedTime(Date lastAcceptedTime) {
		this.lastAcceptedTime = lastAcceptedTime;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
