package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EmployeeSkill generated by hbm2java
 */
public class EmployeeSkill implements java.io.Serializable {

	private Integer id;
	private Boolean status;
	private String skillDetailId;
	private int employeeId;
	private Integer projectId;
	private Integer evaluationType;
	private String description;
	private Integer skillLevelId;
	private Integer expValue;
	private Integer gradeValue;
	private Integer lastModifier;
	private Date lastModifiedTime;
	private Date lastAcceptedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeSkill() {
	}

	public EmployeeSkill(int employeeId, Date insertDatetime) {
		this.employeeId = employeeId;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeSkill(Boolean status, String skillDetailId, int employeeId, Integer projectId,
			Integer evaluationType, String description, Integer skillLevelId, Integer expValue, Integer gradeValue,
			Integer lastModifier, Date lastModifiedTime, Date lastAcceptedTime, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.status = status;
		this.skillDetailId = skillDetailId;
		this.employeeId = employeeId;
		this.projectId = projectId;
		this.evaluationType = evaluationType;
		this.description = description;
		this.skillLevelId = skillLevelId;
		this.expValue = expValue;
		this.gradeValue = gradeValue;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.lastAcceptedTime = lastAcceptedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getSkillDetailId() {
		return this.skillDetailId;
	}

	public void setSkillDetailId(String skillDetailId) {
		this.skillDetailId = skillDetailId;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getEvaluationType() {
		return this.evaluationType;
	}

	public void setEvaluationType(Integer evaluationType) {
		this.evaluationType = evaluationType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getSkillLevelId() {
		return this.skillLevelId;
	}

	public void setSkillLevelId(Integer skillLevelId) {
		this.skillLevelId = skillLevelId;
	}

	public Integer getExpValue() {
		return this.expValue;
	}

	public void setExpValue(Integer expValue) {
		this.expValue = expValue;
	}

	public Integer getGradeValue() {
		return this.gradeValue;
	}

	public void setGradeValue(Integer gradeValue) {
		this.gradeValue = gradeValue;
	}

	public Integer getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(Integer lastModifier) {
		this.lastModifier = lastModifier;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Date getLastAcceptedTime() {
		return this.lastAcceptedTime;
	}

	public void setLastAcceptedTime(Date lastAcceptedTime) {
		this.lastAcceptedTime = lastAcceptedTime;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
