package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EmployeeProfile generated by hbm2java
 */
public class EmployeeProfile implements java.io.Serializable {

	private Integer id;
	private String loginId;
	private int groupId;
	private String firstNameKana;
	private String lastNameKana;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private Boolean gender;
	private Date birthday;
	private String retirementCode;
	private String unemploymentInsuranceCode;
	private String zipCode;
	private String mainAddress;
	private String addressNumber;
	private String houseNumber;
	private String nearestStation;
	private Date prejobEndDate;
	private Boolean status;
	private Integer saleId;
	private String businessType;
	private Integer createdBy;
	private String password;
	private String passwordStatus;
	private Integer passwordExpirePolicy;
	private Date passwordExpireTime;
	private boolean activeFlg;
	private Date lastUpdateDatetime;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeProfile() {
	}

	public EmployeeProfile(String loginId, int groupId, boolean activeFlg, Date insertDatetime) {
		this.loginId = loginId;
		this.groupId = groupId;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeProfile(String loginId, int groupId, String firstNameKana, String lastNameKana, String firstName,
			String lastName, String email, String phone, Boolean gender, Date birthday, String retirementCode,
			String unemploymentInsuranceCode, String zipCode, String mainAddress, String addressNumber,
			String houseNumber, String nearestStation, Date prejobEndDate, Boolean status, Integer saleId,
			String businessType, Integer createdBy, String password, String passwordStatus,
			Integer passwordExpirePolicy, Date passwordExpireTime, boolean activeFlg, Date lastUpdateDatetime,
			Date insertDatetime, Date updateDatetime) {
		this.loginId = loginId;
		this.groupId = groupId;
		this.firstNameKana = firstNameKana;
		this.lastNameKana = lastNameKana;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.gender = gender;
		this.birthday = birthday;
		this.retirementCode = retirementCode;
		this.unemploymentInsuranceCode = unemploymentInsuranceCode;
		this.zipCode = zipCode;
		this.mainAddress = mainAddress;
		this.addressNumber = addressNumber;
		this.houseNumber = houseNumber;
		this.nearestStation = nearestStation;
		this.prejobEndDate = prejobEndDate;
		this.status = status;
		this.saleId = saleId;
		this.businessType = businessType;
		this.createdBy = createdBy;
		this.password = password;
		this.passwordStatus = passwordStatus;
		this.passwordExpirePolicy = passwordExpirePolicy;
		this.passwordExpireTime = passwordExpireTime;
		this.activeFlg = activeFlg;
		this.lastUpdateDatetime = lastUpdateDatetime;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getFirstNameKana() {
		return this.firstNameKana;
	}

	public void setFirstNameKana(String firstNameKana) {
		this.firstNameKana = firstNameKana;
	}

	public String getLastNameKana() {
		return this.lastNameKana;
	}

	public void setLastNameKana(String lastNameKana) {
		this.lastNameKana = lastNameKana;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getRetirementCode() {
		return this.retirementCode;
	}

	public void setRetirementCode(String retirementCode) {
		this.retirementCode = retirementCode;
	}

	public String getUnemploymentInsuranceCode() {
		return this.unemploymentInsuranceCode;
	}

	public void setUnemploymentInsuranceCode(String unemploymentInsuranceCode) {
		this.unemploymentInsuranceCode = unemploymentInsuranceCode;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getMainAddress() {
		return this.mainAddress;
	}

	public void setMainAddress(String mainAddress) {
		this.mainAddress = mainAddress;
	}

	public String getAddressNumber() {
		return this.addressNumber;
	}

	public void setAddressNumber(String addressNumber) {
		this.addressNumber = addressNumber;
	}

	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	public String getNearestStation() {
		return this.nearestStation;
	}

	public void setNearestStation(String nearestStation) {
		this.nearestStation = nearestStation;
	}

	public Date getPrejobEndDate() {
		return this.prejobEndDate;
	}

	public void setPrejobEndDate(Date prejobEndDate) {
		this.prejobEndDate = prejobEndDate;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Integer getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordStatus() {
		return this.passwordStatus;
	}

	public void setPasswordStatus(String passwordStatus) {
		this.passwordStatus = passwordStatus;
	}

	public Integer getPasswordExpirePolicy() {
		return this.passwordExpirePolicy;
	}

	public void setPasswordExpirePolicy(Integer passwordExpirePolicy) {
		this.passwordExpirePolicy = passwordExpirePolicy;
	}

	public Date getPasswordExpireTime() {
		return this.passwordExpireTime;
	}

	public void setPasswordExpireTime(Date passwordExpireTime) {
		this.passwordExpireTime = passwordExpireTime;
	}

	public boolean isActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getLastUpdateDatetime() {
		return this.lastUpdateDatetime;
	}

	public void setLastUpdateDatetime(Date lastUpdateDatetime) {
		this.lastUpdateDatetime = lastUpdateDatetime;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
