package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EmployeeProject generated by hbm2java
 */
public class EmployeeProject implements java.io.Serializable {

	private Integer id;
	private Boolean status;
	private String projectName;
	private int fieldId;
	private Integer employeeId;
	private String fax;
	private Date projectDatetime;
	private int lastModifier;
	private Date lastModifiedTime;
	private Date lastAcceptedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeProject() {
	}

	public EmployeeProject(int fieldId, int lastModifier, Date lastModifiedTime, Date insertDatetime) {
		this.fieldId = fieldId;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeProject(Boolean status, String projectName, int fieldId, Integer employeeId, String fax,
			Date projectDatetime, int lastModifier, Date lastModifiedTime, Date lastAcceptedTime, Boolean activeFlg,
			Date insertDatetime, Date updateDatetime) {
		this.status = status;
		this.projectName = projectName;
		this.fieldId = fieldId;
		this.employeeId = employeeId;
		this.fax = fax;
		this.projectDatetime = projectDatetime;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.lastAcceptedTime = lastAcceptedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public int getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(int fieldId) {
		this.fieldId = fieldId;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getProjectDatetime() {
		return this.projectDatetime;
	}

	public void setProjectDatetime(Date projectDatetime) {
		this.projectDatetime = projectDatetime;
	}

	public int getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(int lastModifier) {
		this.lastModifier = lastModifier;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Date getLastAcceptedTime() {
		return this.lastAcceptedTime;
	}

	public void setLastAcceptedTime(Date lastAcceptedTime) {
		this.lastAcceptedTime = lastAcceptedTime;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
