package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * EvaluationFile generated by hbm2java
 */
public class EvaluationFile implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private Integer uploader;
	private String fileName;
	private String filePath;
	private Date lastModifiedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EvaluationFile() {
	}

	public EvaluationFile(int employeeId, String filePath, Date insertDatetime) {
		this.employeeId = employeeId;
		this.filePath = filePath;
		this.insertDatetime = insertDatetime;
	}

	public EvaluationFile(int employeeId, Integer uploader, String fileName, String filePath, Date lastModifiedTime,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.employeeId = employeeId;
		this.uploader = uploader;
		this.fileName = fileName;
		this.filePath = filePath;
		this.lastModifiedTime = lastModifiedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Integer getUploader() {
		return this.uploader;
	}

	public void setUploader(Integer uploader) {
		this.uploader = uploader;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
