package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * ExperienceDetail generated by hbm2java
 */
public class ExperienceDetail implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean type;
	private int expGroupId;
	private Integer subGroup;
	private Integer dependentId;
	private Integer dependentGroupId;
	private String unit;
	private Boolean checkBox;
	private Short displayOrder;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public ExperienceDetail() {
	}

	public ExperienceDetail(int expGroupId, Date insertDatetime) {
		this.expGroupId = expGroupId;
		this.insertDatetime = insertDatetime;
	}

	public ExperienceDetail(String name, Boolean type, int expGroupId, Integer subGroup, Integer dependentId,
			Integer dependentGroupId, String unit, Boolean checkBox, Short displayOrder, Boolean activeFlg,
			Date insertDatetime, Date updateDatetime) {
		this.name = name;
		this.type = type;
		this.expGroupId = expGroupId;
		this.subGroup = subGroup;
		this.dependentId = dependentId;
		this.dependentGroupId = dependentGroupId;
		this.unit = unit;
		this.checkBox = checkBox;
		this.displayOrder = displayOrder;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public int getExpGroupId() {
		return this.expGroupId;
	}

	public void setExpGroupId(int expGroupId) {
		this.expGroupId = expGroupId;
	}

	public Integer getSubGroup() {
		return this.subGroup;
	}

	public void setSubGroup(Integer subGroup) {
		this.subGroup = subGroup;
	}

	public Integer getDependentId() {
		return this.dependentId;
	}

	public void setDependentId(Integer dependentId) {
		this.dependentId = dependentId;
	}

	public Integer getDependentGroupId() {
		return this.dependentGroupId;
	}

	public void setDependentGroupId(Integer dependentGroupId) {
		this.dependentGroupId = dependentGroupId;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Boolean getCheckBox() {
		return this.checkBox;
	}

	public void setCheckBox(Boolean checkBox) {
		this.checkBox = checkBox;
	}

	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
