package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * Fields generated by hbm2java
 */
public class Fields implements java.io.Serializable {

	private Integer id;
	private int companyId;
	private String fieldName;
	private String type;
	private Short displayOrder;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public Fields() {
	}

	public Fields(int companyId, Date insertDatetime) {
		this.companyId = companyId;
		this.insertDatetime = insertDatetime;
	}

	public Fields(int companyId, String fieldName, String type, Short displayOrder, Boolean activeFlg,
			Date insertDatetime, Date updateDatetime) {
		this.companyId = companyId;
		this.fieldName = fieldName;
		this.type = type;
		this.displayOrder = displayOrder;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
