package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private Integer id;
	private int companyId;
	private String rights;
	private String groupName;
	private String displayName;
	private Integer passwordExpirePolicy;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public Groups() {
	}

	public Groups(int companyId, Date insertDatetime) {
		this.companyId = companyId;
		this.insertDatetime = insertDatetime;
	}

	public Groups(int companyId, String rights, String groupName, String displayName, Integer passwordExpirePolicy,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.companyId = companyId;
		this.rights = rights;
		this.groupName = groupName;
		this.displayName = displayName;
		this.passwordExpirePolicy = passwordExpirePolicy;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getRights() {
		return this.rights;
	}

	public void setRights(String rights) {
		this.rights = rights;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getPasswordExpirePolicy() {
		return this.passwordExpirePolicy;
	}

	public void setPasswordExpirePolicy(Integer passwordExpirePolicy) {
		this.passwordExpirePolicy = passwordExpirePolicy;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
