package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * QacAnswer generated by hbm2java
 */
public class QacAnswer implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private int questionId;
	private String answer;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public QacAnswer() {
	}

	public QacAnswer(int employeeId, int questionId, String answer, Date insertDatetime) {
		this.employeeId = employeeId;
		this.questionId = questionId;
		this.answer = answer;
		this.insertDatetime = insertDatetime;
	}

	public QacAnswer(int employeeId, int questionId, String answer, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.employeeId = employeeId;
		this.questionId = questionId;
		this.answer = answer;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
