package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * QacComment generated by hbm2java
 */
public class QacComment implements java.io.Serializable {

	private Integer id;
	private String questionId;
	private int employeeId;
	private String comment;
	private Integer activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public QacComment() {
	}

	public QacComment(String questionId, int employeeId, String comment, Date insertDatetime) {
		this.questionId = questionId;
		this.employeeId = employeeId;
		this.comment = comment;
		this.insertDatetime = insertDatetime;
	}

	public QacComment(String questionId, int employeeId, String comment, Integer activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.questionId = questionId;
		this.employeeId = employeeId;
		this.comment = comment;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Integer activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
