package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * SkillLevel generated by hbm2java
 */
public class SkillLevel implements java.io.Serializable {

	private Integer id;
	private String groupName;
	private Integer levelGroup;
	private String levelName;
	private String levelValue;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillLevel() {
	}

	public SkillLevel(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public SkillLevel(String groupName, Integer levelGroup, String levelName, String levelValue, Boolean activeFlg,
			Date insertDatetime, Date updateDatetime) {
		this.groupName = groupName;
		this.levelGroup = levelGroup;
		this.levelName = levelName;
		this.levelValue = levelValue;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Integer getLevelGroup() {
		return this.levelGroup;
	}

	public void setLevelGroup(Integer levelGroup) {
		this.levelGroup = levelGroup;
	}

	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public String getLevelValue() {
		return this.levelValue;
	}

	public void setLevelValue(String levelValue) {
		this.levelValue = levelValue;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
