package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * SkillDetail generated by hbm2java
 */
public class SkillDetail implements java.io.Serializable {

	private Integer id;
	private String skillGroupId;
	private String skillName;
	private Integer parentId;
	private Boolean type;
	private Long evaluationType;
	private Long unitId;
	private Integer skillLevel;
	private Integer rootSkill;
	private Integer lft;
	private Integer rgt;
	private Short displayOrder;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillDetail() {
	}

	public SkillDetail(String skillGroupId, Date insertDatetime) {
		this.skillGroupId = skillGroupId;
		this.insertDatetime = insertDatetime;
	}

	public SkillDetail(String skillGroupId, String skillName, Integer parentId, Boolean type, Long evaluationType,
			Long unitId, Integer skillLevel, Integer rootSkill, Integer lft, Integer rgt, Short displayOrder,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.skillGroupId = skillGroupId;
		this.skillName = skillName;
		this.parentId = parentId;
		this.type = type;
		this.evaluationType = evaluationType;
		this.unitId = unitId;
		this.skillLevel = skillLevel;
		this.rootSkill = rootSkill;
		this.lft = lft;
		this.rgt = rgt;
		this.displayOrder = displayOrder;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSkillGroupId() {
		return this.skillGroupId;
	}

	public void setSkillGroupId(String skillGroupId) {
		this.skillGroupId = skillGroupId;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public Long getEvaluationType() {
		return this.evaluationType;
	}

	public void setEvaluationType(Long evaluationType) {
		this.evaluationType = evaluationType;
	}

	public Long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Long unitId) {
		this.unitId = unitId;
	}

	public Integer getSkillLevel() {
		return this.skillLevel;
	}

	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	public Integer getRootSkill() {
		return this.rootSkill;
	}

	public void setRootSkill(Integer rootSkill) {
		this.rootSkill = rootSkill;
	}

	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
