package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * SkillUnit generated by hbm2java
 */
public class SkillUnit implements java.io.Serializable {

	private Integer id;
	private String prefixUnit;
	private String suffixUnit;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillUnit() {
	}

	public SkillUnit(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public SkillUnit(String prefixUnit, String suffixUnit, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.prefixUnit = prefixUnit;
		this.suffixUnit = suffixUnit;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPrefixUnit() {
		return this.prefixUnit;
	}

	public void setPrefixUnit(String prefixUnit) {
		this.prefixUnit = prefixUnit;
	}

	public String getSuffixUnit() {
		return this.suffixUnit;
	}

	public void setSuffixUnit(String suffixUnit) {
		this.suffixUnit = suffixUnit;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
