package vn.yume.cv.orm.po;
// Generated Apr 16, 2018 10:58:41 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;

/**
 * SkillUpdateStatus generated by hbm2java
 */
public class SkillUpdateStatus implements java.io.Serializable {

	private Integer id;
	private Integer employeeId;
	private Integer fieldId;
	private String comment;
	private String status;
	private Integer lastModifier;
	private Date lastModifiedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillUpdateStatus() {
	}

	public SkillUpdateStatus(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public SkillUpdateStatus(Integer employeeId, Integer fieldId, String comment, String status, Integer lastModifier,
			Date lastModifiedTime, Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.employeeId = employeeId;
		this.fieldId = fieldId;
		this.comment = comment;
		this.status = status;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(Integer lastModifier) {
		this.lastModifier = lastModifier;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
